name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Debug Build
        run: cargo build --verbose

      - name: Debug Tests
        run: cargo test --verbose

      - name: Release Build
        run: cargo build --release --verbose

      - name: Release Tests
        run: cargo test --release --verbose